### ISSUE TITLE
Not able to add key pacman-key -r

### ISSUE THREAD

**Issue by harsh1kumar** [bohoomil/fontconfig-ultimate#66]
I am not able to add the key for the repository on Arch. I get the following error:
```
# pacman-key -r 962DDE58
gpg: keyserver receive failed: Connection timed out
==> ERROR: Remote key not fetched correctly from keyserver.
```

I am behind a proxy server, so I think I won't be able to download this key as the port might be blocked. 
So, I would have to use the following command to add the key:
```
# pacman-key --add /path/to/downloaded/keyfile
```
For this I would require the keyfile. I tried search a lot, but was not able to find the keyfile.

Can someone please tell where I can find keyfile for this repository?

**Comment by bohoomil** [comment]
Hello @harsh1kumar I constantly have to write the same thing: GitHub issues *is not* for package related issues. Please, use the [dedicated support thread](https://bbs.archlinux.org/viewtopic.php?id=162098) on Arch Linux Forums where the key-related issues have been discussed dozens of times recently.

By the way, don't you think that this bit

```
gpg: keyserver receive failed: Connection timed out
==> ERROR: Remote key not fetched correctly from keyserver.
```

quite plainly states that the problem is not with the key but the quality of your Internet connection? ;-)
